# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -alh --color=auto'
PS1='[\u@\h \W]\$ '

eval "$(starship init bash)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml
export STARSHIP_CACHE=~/.starship/cache

# Alias Lenovo Vantage CLI
alias svantage='vantage-cli status | lolcat'
alias vantage='sudo vantage-cli conservation | lolcat'

# My Custom Alias
alias clr='clear'
alias ff='fastfetch | lolcat'
alias battery='fastfetch | grep "Battery (L20M2PF0)" | lolcat'
alias ram='fastfetch | grep "Memory" | lolcat'
alias online='fastfetch | grep "Uptime" | lolcat'
alias hmdr='cd ~'
alias cd='z'
alias lgit='lazygit'
alias rm='rm -i'
alias ip='ip -br addr | lolcat'
alias lg='lazygit'
alias Time='date | cut -d " " -f 4 | cut -d : -f 1,2 | lolcat'
alias cpu='sensors | grep Tctl | lolcat'

# --- caido ---
alias caido='cd ~/caido-desktop-x64-linux && ./caido'

# --- trash-cli ---
alias trash='trash-put'
alias list-trash='trash-list'
alias restore-trash='trash-restore'
alias empty-trash='trash-empty'

# --- bat ---
alias pbat='bat -p'
alias bat='bat -pn'
alias cat='pbat'
alias me='whoami'

# --- git ---
alias git-log='git log --oneline --graph --all'
alias git-push='git push --force-with-lease'

# --- burp pro ---
alias burp-pro="burpsuitepro"

# Set up fzf key bindings and fuzzy completion
