# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto --group-directories-first'
alias ll='ls -Alh --color=auto --group-directories-first'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

eval "$(starship init bash)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml
export STARSHIP_CACHE=~/.starship/cache

# History control
HISTCONTROL=ignoredups:erasedups

# Alias Lenovo Vantage CLI
alias svantage='vantage-cli status | lolcat'
alias vantage='sudo vantage-cli conservation | lolcat'

# My Custom Alias
alias clr='clear'
alias ff='fastfetch --config ~/.config/fastfetch/config.json'
alias battery='fastfetch | grep "Battery" | lolcat'
alias ram='fastfetch | grep "Memory" | lolcat'
alias online='fastfetch | grep "Uptime" | lolcat'
alias hmdr='cd ~'
alias cd='z'
alias lgit='lazygit'
alias rm='rm -i'
alias ip='ip -br addr | lolcat'
alias lg='lazygit'
alias ldock='lazydocker'
alias cp='cp -r'
alias Time='date | cut -d " " -f 5 | cut -d ":" -f 1,2 | lolcat'
alias cpu='watch -n 1 sensors'
alias nano='nvim'
alias more='less'
alias burp-pro='burpsuitepro'
alias ai='llama-server --model ~/local-ai/gemma-4-E2B-it-Q4_K_M.gguf --ctx-size 8192 --threads 5 --port 8080'
alias sys-update='sudo pacman -Syyu'
alias app-install='sudo pacman -Syy'
alias snapper-list='sudo snapper list'
alias ebashrc='nvim ~/.bashrc'

# --- trash-cli ---
alias trash='trash-put'
alias list-trash='trash-list'
alias restore-trash='trash-restore'
alias empty-trash='trash-empty'

# --- bat ---
alias pbat='bat -p'
alias bat='bat -pn'
alias cat='pbat'

# --- git ---
alias git-log='git log --oneline --graph --all'
alias git-push='git push --force-with-lease'
alias git-pull='git pull --rebase'

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"

# Setup zoxide
eval "$(zoxide init bash)"

# Setup Yazi
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd < "$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

# Set EDITOR
export EDITOR='nvim'

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/lichi/.lmstudio/bin"
# End of LM Studio CLI section
